/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DisclaimerConfig: typeof import('./src/components/configuration/DisclaimerConfig.vue')['default']
    GeneratorForm: typeof import('./src/components/GeneratorForm.vue')['default']
    GeneratorPreview: typeof import('./src/components/GeneratorPreview.vue')['default']
    LanguageController: typeof import('./src/components/LanguageController.vue')['default']
    MinimalTemplate: typeof import('./src/components/templates/MinimalTemplate.vue')['default']
    PersonalConfig: typeof import('./src/components/configuration/PersonalConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialConfig: typeof import('./src/components/configuration/SocialConfig.vue')['default']
    StyleConfig: typeof import('./src/components/configuration/StyleConfig.vue')['default']
    TheFooter: typeof import('./src/components/ui/TheFooter.vue')['default']
    ThemeController: typeof import('./src/components/ThemeController.vue')['default']
    TheNavbar: typeof import('./src/components/ui/TheNavbar.vue')['default']
    VTabContent: typeof import('./src/components/ui/vTabContent.vue')['default']
    VTabs: typeof import('./src/components/ui/vTabs.vue')['default']
  }
}
