/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DisclaimerConfig: typeof import('./src/components/configuration/DisclaimerConfig.vue')['default']
    GeneratorForm: typeof import('./src/components/GeneratorForm.vue')['default']
    GeneratorPreview: typeof import('./src/components/GeneratorPreview.vue')['default']
    ISystemUiconsDragVertical: typeof import('~icons/system-uicons/drag-vertical')['default']
    LanguageController: typeof import('./src/components/LanguageController.vue')['default']
    PersonalConfig: typeof import('./src/components/configuration/PersonalConfig.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SocialConfig: typeof import('./src/components/configuration/SocialConfig.vue')['default']
    StyleConfig: typeof import('./src/components/configuration/StyleConfig.vue')['default']
    TabContent: typeof import('./src/components/ui/tabs/TabContent.vue')['default']
    TabsWrapper: typeof import('./src/components/ui/tabs/TabsWrapper.vue')['default']
    TemplateConfig: typeof import('./src/components/configuration/TemplateConfig.vue')['default']
    TemplateCorporate: typeof import('./src/components/templates/TemplateCorporate.vue')['default']
    TemplateCreative: typeof import('./src/components/templates/TemplateCreative.vue')['default']
    TemplateDefault: typeof import('./src/components/templates/TemplateDefault.vue')['default']
    TemplateLuxury: typeof import('./src/components/templates/TemplateLuxury.vue')['default']
    TemplateMinimalistic: typeof import('./src/components/templates/TemplateMinimalistic.vue')['default']
    TemplateModern: typeof import('./src/components/templates/TemplateModern.vue')['default']
    TheFooter: typeof import('./src/components/ui/TheFooter.vue')['default']
    ThemeController: typeof import('./src/components/ThemeController.vue')['default']
    TheNavbar: typeof import('./src/components/ui/TheNavbar.vue')['default']
  }
}
